project:
  type: website

website:
  title: "Poseidon introduction for Tübingen University, February 2024"
  sidebar:
    style: "floating"
    search: true
    border: true
    contents:
      - href: index.qmd
        text: Overview
      - section: "Workflow"
        contents:
          - href: backstory.qmd
            text: Backstory
          - href: data_prep.qmd
            text: Data preparation
          - href: ref_pca.qmd
            text: Reference data and PCA
          - href: spacetime.qmd
            text: Spatiotemporal context data
          - href: fstats.qmd
            text: F-statistics
          - href: data_pub.qmd
            text: Data publication
      - href: https://github.com/nevrome/uni.tuebingen.poseidon.intro.2h.2024
        text: This page on GitHub
        icon: github

format:
  html:
    theme: yeti
    css: styles.css
    toc: true



