project:
  type: website

website:
  title: "Poseidon introduction for Tübingen University, February 2024"
  sidebar:
    style: "floating"
    search: true
    border: true
    logo: img/Poseidon-Logo-Horizontal-WhiteLrg.png
    contents:
      - href: index.qmd
        text: Overview
      - section: "Demo"
        contents:
          - icon: envelope
            href: backstory1.qmd
            text: A message from Prof. P.
          - href: data_prep.qmd
            text: Data preparation
          - href: ref_pca.qmd
            text: Reference data and PCA
          - icon: envelope
            href: backstory2.qmd
            text: Prof. P. again
          - href: spacetime.qmd
            text: Spatiotemporal context data
          - href: fstats.qmd
            text: F-statistics
          - icon: envelope
            href: backstory3.qmd
            text: Your publication
          - href: data_pub.qmd
            text: Data publication
      - href: https://github.com/nevrome/uni.tuebingen.poseidon.intro.2h.2024
        text: This page on GitHub
        icon: github

format:
  html:
    theme: slate
    css: styles.css
    toc: false
    bibliography: references.bib



